# the structure of this yaml simulates the info in real transaction
# change if needed
tockaccount:
    username: A654332
    password: wonder123
futuresaccount:
    username: F345677
    password: wonder321
sinfo:
    ip:  100.102.121.116
    port: "35532"
finfo:
    ip:  101.102.121.100
    port: "35531"