---
# viper's GetStringMap function makes key value lowercase
targetprop:
  stock:
    st:
        contractsize:  100.0
        transferfeerate:  0.00001
        taxrate:  0.001
        commbrokerrate:  0.0000687
    mainboard:
        contractsize:  100.0
        transferfeerate:  0.00001
        taxrate:  0.001
        commbrokerrate:  0.0000687
    star:
        contractsize:  100.0
        transferfeerate:  0.00001
        taxrate:  0.001
        commbrokerrate:  0.0000687
    chinext:
        contractsize:  100.0
        transferfeerate:  0.00001
        taxrate:  0.001
        commbrokerrate:  0.0000687
    etf:
        contractsize:  100.0
        transferfeerate:  0.00001
        taxrate:  0.0
        commbrokerrate:  0.0000687

  futures:
    au2210:
        contractsize:  1000.0
        ticksize:  0.02
        marginlong:  10.0
        marginshort:  10.0
        marginbroker:  0.0
        iscommratetype: false
        commopen:  2.0
        commclosetoday:  0.0
        commcloseprevious:  2.0
        commbroker:  0.01

...